language: csharp
mono: none
#match on https://www.microsoft.com/net/download/linux
dotnet: 2.0.0
sudo: required
dist: trusty

services:
  - docker

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
    - curl


script:
  - which dotnet
  - dotnet --info

after_success:
  # Build
  - pushd src/
  - dotnet restore
  - pushd BuildIndicatron.Server.Core
  - dotnet publish   --version-suffix $TRAVIS_BUILD_NUMBER -c Release -o bin/publish
  - popd
  - docker build  -t rolfwessels/buildindicator:v0.0.$TRAVIS_BUILD_NUMBER-beta -f Dockerfile.arm32 .
  # Add docker images
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t rolfwessels/buildindicator:latest  -t rolfwessels/buildindicator:v0.0.$TRAVIS_BUILD_NUMBER -f Dockerfile.arm32 .
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push rolfwessels/buildindicator;
    fi