language: csharp
mono: none
#match on https://www.microsoft.com/net/download/linux
dotnet: 2.0.0
sudo: required
dist: trusty

services:
  - docker

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
    - curl


script:
  - which dotnet
  - dotnet --info

after_success:
  # Build
  - pushd src/
  - dotnet restore
  - pushd BuildIndicatron.Server
  - sed -e "s/Version\>.*\</Version>1.0.$TRAVIS_BUILD_NUMBER\</g" BuildIndicatron.Server.csproj;
  - if [ "$TRAVIS_BRANCH" == "master" ]; 
    then
    dotnet publish  -c Release -o bin/publish;
    else
    dotnet publish   --version-suffix beta -c Release -o bin/publish;
    fi
  - popd
  # Add docker images
  - if [ "$TRAVIS_BRANCH" == "master" ]; 
    then
    docker build -t rolfwessels/buildindicator:latest  -t rolfwessels/buildindicator:v1.0.$TRAVIS_BUILD_NUMBER -f Dockerfile.arm32 .;
    else
    docker build  -t rolfwessels/buildindicator:beta -t rolfwessels/buildindicator:v1.0.$TRAVIS_BUILD_NUMBER-beta -f Dockerfile.chip .;
    fi
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push rolfwessels/buildindicator;