language: csharp
mono: none #latest
#match on https://www.microsoft.com/net/download/linux
dotnet: 2.0.0
sudo: required
dist: trusty

services:
  - docker

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
    - curl


script:
   # Build chip
  - pushd src/
  - dotnet restore
  
  # Chip
  - pushd BuildIndicatron.Server.Chip
  - sed -i -e "s/<Version>[0-9\.]*</<Version>1.0.$TRAVIS_BUILD_NUMBER\</g" BuildIndicatron.Server.Chip.csproj;
  - if [ "$TRAVIS_BRANCH" == "master" ]; 
    then
    dotnet publish -c Release -r linux-arm -o bin/publish;
    else
    dotnet publish --version-suffix beta -c Release -r linux-arm -o bin/publish;
    fi
  - popd
  # Add docker images
  
  - if [ "$TRAVIS_BRANCH" == "master" ]; 
    then
    docker build -t rolfwessels/buildindicator:chip  -t rolfwessels/buildindicator:v1.0.$TRAVIS_BUILD_NUMBER-chip -f Dockerfile.chip .;
    else
    docker build -t rolfwessels/buildindicator:chip-beta -t rolfwessels/buildindicator:v1.0.$TRAVIS_BUILD_NUMBER-chip-beta -f Dockerfile.chip .;
    fi

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push rolfwessels/buildindicator;