os: Visual Studio 2017
install:

build_script:
  # dotnet info
  - ps: dotnet --info
  - ps: cd src
  - ps: dotnet restore
  # Pi
  - ps: cd BuildIndicatron.Server.Pi
#  - sed -i -e "s/<Version>[0-9\.]*</<Version>1.0.$TRAVIS_BUILD_NUMBER\</g" BuildIndicatron.Server.Pi.csproj;
# - if [ "$TRAVIS_BRANCH" == "master" ]; 
#   then
   dotnet publish -c Release -o bin/publish;
#   else
#   dotnet publish --version-suffix beta -c Release -o bin/publish;
#   fi
# - popd
# # Add docker images
# - if [ "$TRAVIS_BRANCH" == "master" ]; 
#   then
#   docker build -t rolfwessels/buildindicator:rpi-mono  -t rolfwessels/buildindicator:v1.0.$TRAVIS_BUILD_NUMBER-rpi-mono -f Dockerfile.chip .;
#   else
#   docker build -t rolfwessels/buildindicator:rpi-mono-beta -t rolfwessels/buildindicator:v1.0.$TRAVIS_BUILD_NUMBER-rpi-mono-beta -f Dockerfile.chip .;
#   fi
#  - ps: dotnet vstest (Get-ChildItem test | Where-Object {!$_.FullName.contains('Sdk') } | % { Join-Path $_.FullName -ChildPath ("bin/Debug/netcoreapp1.1/$($_.Name).dll") })
#  - ps: move testresults\*.trx testresults\result.trx
#  - ps: $wc = New-Object 'System.Net.WebClient'
#  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\testresults\result.trx))

  # - ps: cd test\CoreDocker.Sdk.Tests
  # - ps: dotnet test 
  # - ps: cd ..\..


test: off 
version: 0.0.1.{build}
