os: Visual Studio 2017
install:

build_script:
  # dotnet info
  - ps: dotnet --info
  - ps: cd src
  - ps: dotnet restore
  # Pi
  - ps: cd BuildIndicatron.Server.Pi
#  - sed -i -e "s/<Version>[0-9\.]*</<Version>1.0.%APPVEYOR_BUILD_NUMBER%\</g" BuildIndicatron.Server.Pi.csproj;
  - ps: if($env:APPVEYOR_REPO_BRANCH -eq 'master') {
        dotnet publish -c Release -o bin/publish
      }
      else {
        dotnet publish --version-suffix beta -c Release -o bin/publish
      }
  - cd ..
  - echo %APPVEYOR_REPO_BRANCH%
# # Add docker images
# - if [ "$TRAVIS_BRANCH" == "master" ]; 
#   then
#   docker build -t rolfwessels/buildindicator:rpi-mono  -t rolfwessels/buildindicator:v1.0.%APPVEYOR_BUILD_NUMBER%-rpi-mono -f Dockerfile.rpi-mono .;
#   else
  
  # - docker build -t rolfwessels/buildindicator:rpi-mono-beta -t rolfwessels/buildindicator:v1.0.%APPVEYOR_BUILD_NUMBER%-rpi-mono-beta -f Dockerfile.rpi-mono .
  

artifacts:
  - path: 'src\BuildIndicatron.Server.Pi\bin\publish\**\*'
    name: buildindicator v1.0.%APPVEYOR_BUILD_NUMBER%
    type: zip

    

test: off 
version: 0.0.1.{build}
