#! /bin/bash

# /etc/init.d/buildindicator



### BEGIN INIT INFO
# Provides:          buildindicator
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts my build indicator when the system starts
# Description:       A simple script which will start / stop buildindicator at boot /$
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting !"
    sleep 2s
    cd /home/pi/buildIndicatron.server
    echo "Check /home/pi/buildIndicatron.server/runner.log for output"
    sudo nohup mono /home/pi/buildIndicatron.server/BuildIndicatron.Server.exe > /home/pi/buildIndicatron.server/buildIndicatron.server.out &
    ;;
  stop)
    echo "Bye!"
    killall mono
    exit 1
    ;;
  *)
    echo "Bye!"
    killall mono
    exit 1
    ;;
esac

exit 0 