---
- name: Download Docker install script
  get_url:
    url: https://get.docker.com
    dest: ~/install_docker.sh

- name: Install Docker
  command: sh ./install_docker.sh
  args:
    creates: /usr/bin/docker
  become: True

- name: Add pi to docker group
  user:
    name: '{{ ansible_ssh_user }}'
    groups: docker
    append: yes
  become: True


- name: Allow external access to docker
  become: True
  lineinfile: dest=/etc/default/docker
              regexp="^.*DOCKER_OPTS="
              line="DOCKER_OPTS=\"-H tcp://127.0.0.1:2375\""
              state=present
  notify: restart docker

