- name: Create docker folder
  file:
    path: ~/docker/portainer/
    state: directory
- name: Create portainer compose file
  copy:
    src: docker-compose.yml
    dest: ~/docker/portainer/docker-compose.yml

- name: Docker up portainer
  command: docker-compose up -d
  become: true
  args:
    chdir: '{{ home_dir }}/docker/portainer/'

# - name: Run Docker Portainer
#   docker_container:
#     name: portainer
#     image: portainer/portainer:{{ portainer_version }}
#     state: present
#     recreate: yes
#     privileged: yes
#     restart_policy: unless-stopped
#     links:
#       - db:mysql
#     ports:
#       - "9000:9000"
#     volumes:
#       - /data/portainer:/data
#       - /var/run/docker.sock:/var/run/docker.sock
