FROM microsoft/dotnet:2.0.0-runtime AS build-env
WORKDIR /app

# copy everything else and build
COPY ./ ./
RUN dotnet restore
WORKDIR /app/BuildIndicatron.Server
RUN dotnet publish -c Release -o out

# build runtime image
FROM microsoft/dotnet:2.0.0-runtime-stretch-arm32v7
WORKDIR /app
COPY --from=build-env /app/BuildIndicatron.Server/out ./
ENTRYPOINT ["dotnet", "dotnetapp.dll"]
