---
- hosts: all
  become: yes

  tasks:
  - name: Make sure we have a 'wheel' group
    group:
      name=wheel
      state=present

  - name: Add Unix Admins users
    user: name='{{ansible_ssh_user}}' group=users groups=wheel

  - name: Allow wheel group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'

  - name: Disallow root SSH access
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PermitRootLogin"
                line="PermitRootLogin no"
                state=present