- name: dependency provisioning
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: apt-get update
      become: yes
      raw: sudo apt-get update
    - name: install python
      become: yes
      raw: sudo apt-get -y install python-apt
      